import { ValidCategory, ValidExpType, ValidSkills } from "./constants";

interface PagesInfoInterface {
  title: string;
  imgArr: string[];
  linkURL?: string;
  description?: string;
}

interface DescriptionDetailsInterface {
  paragraphs: string[];
  bullets: string[];
}

export interface ExperienceInterface {
  id: string;
  type: ValidExpType;
  companyName: string;
  category: ValidCategory[];
  shortDescription: string;
  websiteLink?: string;
  githubLink?: string;
  techStack: ValidSkills[];
  startDate: Date;
  endDate: Date;
  companyLogoImg: any;
  descriptionDetails: DescriptionDetailsInterface;
  pagesInfoTitle?: string;
  pagesInfoArr: PagesInfoInterface[];
}

export const Experiences: ExperienceInterface[] = [
  {
    id: "dna-quality-control-toolkit",
    companyName: "DNA QC Toolkit",
    type: "Personal Project",
    category: ["Bioinformatics", "Computational Bioengineering", "UI/UX"],
    shortDescription:
      "Developed and optimized a high-performing quality control toolkit for DNA sequence analysis, emphasizing efficiency and accuracy.",
    websiteLink: "https://github.com/aahmeddev/QC-Toolkit/",
    techStack: ["Java", "Python", "Git", "HTML 5", "JavaFX", "Biopython"],
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-27"),
    companyLogoImg: "/projects/dna-quality-control-toolkit/QClogo.png",
    pagesInfoTitle: "Features",
    pagesInfoArr: [
      {
        title: "Welcome Page",
        description:
          "Select .fastq/fastq.gz file for quality analysis, dragging from file explorer or browsing locally.",
        imgArr: ["/projects/dna-quality-control-toolkit/welcome_page.png"],
      },
      {
        title: "Base Statistics",
        description:
          "Get a quality overview for the selected tab's data, and the core information, including areas of concern to do with the data.",
        imgArr: ["/projects/dna-quality-control-toolkit/base_statistics.png"],
      },
      {
        title: "Data Visualisation",
        description:
          "Select between 10 different plots, and learn essential information on the base sequences and dataset information. See these examples from a good quality dataset:",
        imgArr: ["/projects/dna-quality-control-toolkit/data_examples.png"],
      },
      {
        title: "Data Trimming",
        description:
          "Remove adapter and poor quality sequences, allowing for an overrall better quality dataset",
        imgArr: ["/projects/dna-quality-control-toolkit/trimming.png"],
      },
      {
        title: "Export to HTML",
        description:
          "Export the report as an interactive HTML, allowing it to be shared and saved.",
        imgArr: [],
        linkURL:
          "/projects/dna-quality-control-toolkit/SRR490124_2_quality_report.html",
      },
    ],
    descriptionDetails: {
      paragraphs: [
        "In any DNA sequencing project, the raw data generated by sequencing machines is the foundation for all subsequent discoveries. However, this raw data is rarely perfect. It can contain a range of technical errors and artifacts, such as low-quality reads, leftover adapter sequences from the lab process, and other biases.",
        "This is where a Quality Control (QC) application comes in. It serves as the first and most critical checkpoint in the bioinformatics pipeline. Before any meaningful biological analysis can begin—such as aligning reads to a genome or identifying mutations—researchers must first use a tool like this one to assess the health of their raw data",
        "By generating a comprehensive summary of data quality, these applications allow scientists to diagnose potential issues. Based on the QC report, a researcher can then make an informed decision: either the data is of high quality and ready for analysis, or it needs to be cleaned (e.g., by trimming adapters and low-quality ends) to ensure that the final scientific conclusions are accurate and reliable. To get a deeper understanding of the quality control process, I made an amateur DNA QC Toolkit, inspired by applications like FastQC.",
        "A key part of this project was developing a deep understanding of the FASTQ file format, including how to parse its four-line structure to extract both the DNA sequences and their corresponding Phred quality scores. I researched and implemented the logic for several essential quality control (QC) metrics, such as Per-Base Sequence Quality, GC Content, Sequence Duplication Levels, and Adapter Contamination, ensuring the application provides a scientifically valid analysis.",
        "The underlying application logic, including file I/O and data manipulation, was implemented in Java. For the user interface, JavaFX and FXML were used to create a user-friendly and responsive graphical application with the multi-tabbed design. To prevent UI freezing while performing analysis of large files, I implemented a multi-threaded system based on Java's ExecutorService where all intensive computations are performed on background threads.",
        "All plots are visualized using a Python backend. The central Java application governs and communicates with external Python processes. This option leverages the strengths and versatility of the Matplotlib library to generate the entire range of scientific plots and tables required for final analysis reports.",
      ],
      bullets: [],
    },
  },
  {
    id: "nanopore-basecalling",
    companyName: "Nanopore Basecalling",
    type: "Personal Project",
    category: ["Web Dev", "UI/UX"],
    shortDescription:
      "Developed a user-friendly website for Inscript Hindi typing, addressing the need for a simple tool for Hindi writers to convey data digitally.",
    websiteLink: "https://hindityping.namanbarkiya.xyz",
    githubLink: "https://github.com/namanbarkiya/inscript-hindi-keyboard",
    techStack: ["HTML 5", "C++", "Javascript"],
    startDate: new Date("2022-05-01"),
    endDate: new Date("2022-06-15"),
    companyLogoImg: "/projects/hindi-keyboard/logo.png",
    pagesInfoTitle: "Functions",
    pagesInfoArr: [
      {
        title: "Typing Interface",
        description: "Minimal and user-friendly Inscript Hindi typing area",
        imgArr: ["/projects/hindi-keyboard/web_1.png"],
      },
      {
        title: "Copy and Download the file",
        description:
          "Export functionality allowing users to copy text or download as a document file",
        imgArr: [
          "/projects/hindi-keyboard/web_2.png",
          "/projects/hindi-keyboard/web_3.png",
        ],
      },
    ],
    descriptionDetails: {
      paragraphs: [
        "The 'Inscript Hindi Typing Website' project emerged from the need to provide a simple and accessible tool for Hindi writers, especially those in digital news and media, who wished to convey data in Hindi.",
        "Recognizing the challenges posed by complex software in the market, I set out to create a minimalistic typing area that catered to the needs of a vast community of Hindi typists in India.",
        "The project was designed to address the specific requirements of users familiar with the Inscript keyboard layout, mapping English and Hindi alphabets for seamless typing. The intuitive interface allowed users to effortlessly switch between languages, streamlining the process of content creation.",
        "Leveraging HTML and CSS, I crafted the website's UI to ensure a user-friendly experience. Additionally, Local Storage was utilized to enable users to save and retrieve their work, enhancing convenience and productivity.",
        "The website's focus on user experience and simplicity proved to be a key factor in its popularity among Hindi writers. By offering a tool that reduced the barriers to entry, I contributed to the digital empowerment of Hindi typists who previously faced challenges in conveying their message effectively.",
        "This project marked one of my initial forays into web development and highlighted the transformative potential of technology in addressing real-world challenges.",
      ],
      bullets: [
        "Developed a user-friendly website for Inscript Hindi typing.",
        "Catered to the needs of Hindi writers in digital news and media.",
        "Created a minimalistic and intuitive typing interface for the Inscript keyboard layout.",
        "Mapped English and Hindi alphabets to provide a seamless typing experience.",
        "Utilized HTML and CSS to design a user-friendly UI.",
        "Implemented Local Storage to enable users to save and retrieve their work.",
        "Contributed to the digital empowerment of Hindi typists by offering a simple tool.",
        "Marked one of my first web development projects, showcasing technology's potential for addressing real-world needs.",
      ],
    },
  },
];

export const featuredExperiences = Experiences.slice(0, 3);
